### ISSUE TITLE
where to download the pre-trained embeddings 'embedding/bio_embedding.txt'

### ISSUE THREAD

**Issue by loveJasmine** [shangjingbo1226/AutoNER#1]
or whether it can be replaced by glove.6B.300.txt ?

**Comment by shangjingbo1226** [comment]
I will put a link to that soon.

**Comment by shangjingbo1226** [comment]
You can download it here: http://dmserv4.cs.illinois.edu/bio_embedding.txt. I have also updated the README.

**Comment by DrozdikGleb** [comment]
@shangjingbo1226, where to download the pre-trained embedding/bio_embedding.txt? This link http://dmserv4.cs.illinois.edu/bio_embedding.txt is not available (ERR_CONNECTION_REFUSED)

**Comment by 1d2-cpu** [comment]
> 您可以在此处下载：http://dmserv4.cs.illinois.edu/bio_embedding.txt。我还更新了 README。
您好 在我想请问一下 这个链接访问失败了 如何才能获取该文本呢
