### ISSUE TITLE
multi tag?

### ISSUE THREAD

**Issue by phiedulxp** [shangjingbo1226/AutoNER#12]
```
	label mapping: check --> 1
	label mapping: disease --> 2
	label mapping: food --> 3
	label mapping: drug --> 4
	label mapping: symptom --> 5
	label mapping: body --> 6
	label mapping: S --> 7
	label mapping: operation --> 8
	label mapping: D --> 9
	label mapping: check,drug --> 10
	label mapping: drug,operation --> 11

```
S for what ?
D for what ?
the last two means multi-tag?

**Comment by shangjingbo1226** [comment]
I have explained S&D in another thread.

Not sure where did you get the label mapping? If it's the label mapping from the types to the numbers, S and D should not be there and every different type must be assigned a unique number.
