### ISSUE TITLE
two input docs(dict_core&dict_full)

### ISSUE THREAD

**Issue by Rock-L** [shangjingbo1226/AutoNER#19]
hi Jingbo:

your model need two input files (dict_core&dict_full), and i find that the dict_full contains dict_core. so why don't you combine the two files ,and annotate all words?

thands.

**Comment by shangjingbo1226** [comment]
Entities in dict_core require type information. Also, they are expected to high-precision (e.g, > 90%) and relatively-low-recall (e.g., ~50%) string matching results.

While dict_full only needs the phrase without type information. Moreover, they are expected to high-recall (e.g, > 90%) and relatively-low-precision (e.g., ~50%) string matching results.
