### ISSUE TITLE
Dictionaries used in the paper and other bio medical dataset

### ISSUE THREAD

**Issue by manikbhandari** [shangjingbo1226/AutoNER#20]
Hi, thanks for sharing your implementation. I loved reading your paper and have some doubts.
In your [paper](https://arxiv.org/pdf/1809.03599.pdf) you mentioned using 

> MeSH database and the CTD Chemical and Disease vocabularies. The dictionary contains 322,882 Chemical and Disease entity surfaces.

Whereas the dictionary provided contains much fewer terms. 
1. Did you use the provided dictionary for the results presented in the paper? 
2. Also, is the same provided dictionary used for NCBI-disease dataset?
3. Would it be possible to share the datasets and dictionaries used for other datasets?

**Comment by shangjingbo1226** [comment]
The statistics are presented in the paper is the original dictionary. We did more process to the dictionary and obtain the refined ones. The refined ones are included in this repo.

NCBI and BC5CRD have different entity type sets. Also, their raw texts are different. So after the processing, we have a different dictionary for NCBI.

Please send me an email if you are interested in other dictionaries. For the NER datasets, I believe you need to find it online, as they have their own license and rules for distribution.
