### ISSUE TITLE
Difference in the performance of autoNER when the high-quality phrases are not involved?

### ISSUE THREAD

**Issue by nooralahzadeh** [shangjingbo1226/AutoNER#21]
In table 4, it seems the high-quality phrases provides a large effect on the performance.
And when you compare it with the fuzzy CRF, it seems the Fuzzy CRF outperform the tie-break mechanism, if you do not involve the high-quality phrases.
Could you elaborate more on that?

**Comment by shangjingbo1226** [comment]
Fuzzy-CRF Model always use high-quality phrases. The "unknown" type brought by high-quality phrases is the reason that we want to use the Fuzzy-CRF layer.
