### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by Rock-L** [shangjingbo1226/AutoNER#22]
hi:
when i trained the model , i got the error like:
![image](https://user-images.githubusercontent.com/22190647/53388194-2e525900-39c5-11e9-8121-45834c66a79c.png)

so i print the system mem every epoch, i find that the available mem decrease every epoch, the process like:
![image](https://user-images.githubusercontent.com/22190647/53388332-b3d60900-39c5-11e9-96d9-c96c3f6fa095.png)
![image](https://user-images.githubusercontent.com/22190647/53388339-ba648080-39c5-11e9-909e-6eb6371058c7.png)
![image](https://user-images.githubusercontent.com/22190647/53388344-bfc1cb00-39c5-11e9-9530-b31d63df31a9.png)
![image](https://user-images.githubusercontent.com/22190647/53388350-c4867f00-39c5-11e9-915c-bc0f1e39e0f4.png)
![image](https://user-images.githubusercontent.com/22190647/53388353-c94b3300-39c5-11e9-9f42-ff7917e9f126.png)
![image](https://user-images.githubusercontent.com/22190647/53388357-ec75e280-39c5-11e9-9098-41d43d37e302.png)
![image](https://user-images.githubusercontent.com/22190647/53388379-da943f80-39c5-11e9-8137-e4f145bf7563.png)

i think every epoch should release the mem , and it's seems not , how can i fix this error? thanks

ps :
dict_core:1000 lines(phrase)
dict_full:2000 lines(phrase)
raw_text:20w lines(words)

**Comment by shangjingbo1226** [comment]
We will take a look at this. Thanks for pointing it out!

**Comment by Rock-L** [comment]
> We will take a look at this. Thanks for pointing it out!

hi:
have u find something wrong?

**Comment by LiyuanLucasLiu** [comment]
We did some experiments and didn't reproduce the increase of memory usage (w. our data).

Here are some guesses & TODOs:

1. upgrade the `torch-scope` to `0.5.1`;
2. make sure to use `pytorch 1.0`;
3. comment the model saving commend during model training;

Best luck to your experiments.
