### ISSUE TITLE
LaptopReview dataset

### ISSUE THREAD

**Issue by nooralahzadeh** [shangjingbo1226/AutoNER#26]
Hi, 
Is it possible to share the Raw Sent. dataset and dictionary that you used in experiments for LaptopReview dataset?

Thanks.

**Comment by shangjingbo1226** [comment]
The raw sentences are able to be downloaded from the SemEval dataset website. If you are interested in the dictionaries, please send me an email to shangjingbo AT gmail.com. I will share it with you. Thanks!
