### ISSUE TITLE
Does it work for single label?

### ISSUE THREAD

**Issue by shivam1702** [shangjingbo1226/AutoNER#27]
I was trying to run the model for single label, i.e. marking out all the Technical terms, created relevant datasets, and dictionaries. But during training the model doesn't show any progress bar, nor trains the model. 
Finally, it shows the F1 to be -inf on dev.

Does this model work for single label NER?

**Comment by shangjingbo1226** [comment]
It should work for "single label". We have done something similar on the laptop reviews.  What's your corpus and dictionaries?
