### ISSUE TITLE
Question about the results for LaptopReview

### ISSUE THREAD

**Issue by nooralahzadeh** [shangjingbo1226/AutoNER#30]
Hi,
Could you please let me know, how you did experiments on LaptopReviwe dataset,
what were the Gold and Distant supervision datasets? Because the gold has 3,845 sentences, and in Figure 3.C it seems that you used another dataset (raw text)  for Distantly supervised annotation!

And if it is possible to give me the last scores of AutoNER-Gold-DistantSupervision for Figure 3.a and 3.c where it uses all of the training set. 

Thanks
Farhad

**Comment by shangjingbo1226** [comment]
I have just emailed the LaptopReview dataset's dictionary to you. We are using exactly the same training/testing data as the SemEval setting.
