### ISSUE TITLE
For reproducing the experimental results with LaptopReview dataset

### ISSUE THREAD

**Issue by yahshibu** [shangjingbo1226/AutoNER#35]
Hello, 
Thank you for sharing your code!

I would like to follow your experiments. I can do the same experiments with BC5CDR (according to Readme) and NCBI-Disease (according to the descriptions in your paper).
But, I cannot follow the completely same way for LaptopReview. In order to do that, I need a "domain-specific dictionary" and an "unknown-typed high-quality phrase" list.

I'm not sure that the source of the domain-specific dictionary has not been changed since then.
Could you share the dictionary with us?

In terms of the high-quality phrase list, we will make the same list with your "[AutoPhrase](https://github.com/shangjingbo1226/AutoPhrase)" and [Amazon laptop reviews](http://times.cs.uiuc.edu/~wang296/Data/) as you say in your paper.
But, some preprocessing is required to feed the review dataset into AutoPhrase and there are some options about it. For example, whether or not we include the titles of the reviews, what sentence splitter we will use, and so on.
I would appreciate it if you could share the high-quality phrase list.

Thanks.

**Comment by yahshibu** [comment]
In addition, we cannot access the website of SemEval 2014 now (as of Oct. 16th in 2019).
http://alt.qcri.org/semeval2014/task4/index.php?id=data-and-tools

I would like the dataset itself...

Thanks.

**Comment by shangjingbo1226** [comment]
Could you please send an email to me? shangjingbo AT gmail. I will send the dataset to you.
