### ISSUE TITLE
Can autoner be applied to Chinese NER?

### ISSUE THREAD

**Issue by djxprogrammer** [shangjingbo1226/AutoNER#36]
Firstly, I appreciate your works very much. Now I wanna do some experiments on the task of chinese ner. SO my question is : 
     1.whether it is possible or not? yes or no,
     2.if yes is for the first question, then what are the changes should be made?
Thank you in advance~~~

**Comment by shangjingbo1226** [comment]
It should be doable but there might be some encoding issues.
