### ISSUE TITLE
subprocess.CalledProcessError: Command '['tput', 'cols']' 

### ISSUE THREAD

**Issue by SunyanGu** [shangjingbo1226/AutoNER#43]
This problem appeared from "from torch_scope import wrapper"  and in line 47 "COLS = int(subprocess.check_output(shlex.split('tput cols')))",Is there anything I didn't install？

**Comment by SunyanGu** [comment]
need to install  ncurses
conda install -c r ncurses

**Comment by syw2014** [comment]
Same problem,and fix  it with "export TERMINFO=/usr/share/terminfo", link here:[tput: unknown terminal](https://stackoverflow.com/questions/799576/tput-unknown-terminal)
